build: false
version: '{branch}-{build}'

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINCONDA: C:\Miniconda3

image: Ubuntu

init:
  - python3 -m pip install pytest

install:
  - python setup.py install

test_script:
  - pytest

