build: false
version: '{branch}-{build}'

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINCONDA: C:\Miniconda3

image: Ubuntu


install:
  - pip install -U setuptools
  - python3 setup.py install

test_script:
  - pip install pytest
  - pytest

